/*
 * Generated by bedrock-dumper v1.0
 * Target: Minecraft.Windows.exe
 * Timestamp: 2026-09-26 18:27:16 UTC
 * Elapsed: 6718 ms
 * Total Offsets: 2
 */

#pragma once
#include <cstdint>

namespace Offsets {
    namespace ClientInstance {
        constexpr uintptr_t Update = 0xD44840; // xref to textures/ui/pointer
        constexpr uintptr_t GetLocalPlayer = 0xD4BE50; // vtable slot from update
    }
} // namespace Offsets
