/*
 * Generated by bedrock-dumper v1.0
 * Target: Minecraft.Windows.exe
 * Timestamp: 2026-09-26 17:51:15 UTC
 * Elapsed: 8236 ms
 * Total Offsets: 1
 */

#pragma once
#include <cstdint>

namespace Offsets {
    namespace ClientInstance {
        constexpr uintptr_t Update = 0xD44840; // xref to textures/ui/pointer
    }
} // namespace Offsets
