#include "writer.h"
#include "config.h"
#include "dumper/dumper.h"
#include "process/process.h"
#include <chrono>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <nlohmann/json.hpp>
#include <spdlog/spdlog.h>
#include <sstream>

namespace dumper::writer {

    static auto utc_timestamp() -> std::string {
        const auto now = std::chrono::system_clock::now();
        const auto t = std::chrono::system_clock::to_time_t(now);
        std::tm tm{};
        gmtime_s(&tm, &t);
        char buf[64];
        std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S UTC", &tm);
        return buf;
    }

    auto IWriter::write(const std::string& filename, std::chrono::milliseconds elapsed_time)
        -> bool {
        try {
            std::string final_filename = filename;
            std::string ext = get_file_extension();
            if (final_filename.length() < ext.length() ||
                final_filename.compare(final_filename.length() - ext.length(), ext.length(), ext) != 0) {
                final_filename += ext;
            }

            std::filesystem::path output_path = std::filesystem::current_path() / final_filename;
            std::ofstream file(output_path);
            if (!file.is_open()) {
                spdlog::error("Failed to open file for writing: {}", output_path.string());
                return false;
            }

            file << generate_header_comment(elapsed_time);
            file << generate_content();
            file.close();

            spdlog::info("Output written to: {}", output_path.string());
            return true;
        } catch (const std::exception& e) {
            spdlog::error("Writer error: {}", e.what());
            return false;
        }
    }

    auto IWriter::generate_header_comment(std::chrono::milliseconds elapsed_time) -> std::string {
        std::ostringstream ss;
        ss << "/*\n"
           << " * Generated by " << PROJECT_NAME << " v" << PROJECT_VERSION << "\n"
           << " * Target: Minecraft.Windows.exe\n"
           << " * Timestamp: " << utc_timestamp() << "\n"
           << " * Elapsed: " << elapsed_time.count() << " ms\n"
           << " * Total Offsets: " << g_dumper.get_total_offset_count() << "\n"
           << " */\n\n";
        return ss.str();
    }

    auto HeaderWriter::generate_content() -> std::string {
        std::ostringstream ss;
        ss << "#pragma once\n"
           << "#include <cstdint>\n\n"
           << "namespace Offsets {\n";

        std::lock_guard<std::mutex> lock(g_dumper.m_offset_mutex);
        for (const auto& [ns, entries] : g_dumper.m_offsets) {
            ss << "    namespace " << ns << " {\n";
            for (const auto& entry : entries) {
                ss << "        constexpr uintptr_t " << entry.name << " = 0x"
                   << std::uppercase << std::hex << entry.offset << ";";
                if (!entry.comment.empty()) {
                    ss << " // " << entry.comment;
                }
                ss << "\n";
            }
            ss << "    }\n";
        }

        ss << "} // namespace Offsets\n";
        return ss.str();
    }

    auto JsonWriter::generate_header_comment(std::chrono::milliseconds) -> std::string {
        return ""; // Pure JSON requires no C-style comments
    }

    auto JsonWriter::generate_content() -> std::string {
        nlohmann::ordered_json root;
        root["_metadata"] = {
            {"project", PROJECT_NAME},
            {"version", PROJECT_VERSION},
            {"timestamp", utc_timestamp()},
            {"total_offsets", g_dumper.get_total_offset_count()}
        };

        std::lock_guard<std::mutex> lock(g_dumper.m_offset_mutex);
        for (const auto& [ns, entries] : g_dumper.m_offsets) {
            nlohmann::ordered_json ns_json;
            for (const auto& entry : entries) {
                std::ostringstream hex_val;
                hex_val << "0x" << std::uppercase << std::hex << entry.offset;
                ns_json[entry.name] = {
                    {"rva", hex_val.str()},
                    {"decimal", entry.offset},
                    {"comment", entry.comment}
                };
            }
            root["offsets"][ns] = ns_json;
        }

        return root.dump(4);
    }

} // namespace dumper::writer
